version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.13
    container_name: rabbitmq_container
    ports:
      - "5552:5552"
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_stream advertised_host localhost"
    networks:
      - rabbitmq_net

  debian:
    image: debian:latest
    container_name: debian_container
    stdin_open: true
    tty: true
    volumes:
      - ./working_directory:/usr/src/app  # mounting the local directory so you can code on your local machine directly
    networks:
      - rabbitmq_net
    depends_on:
      - rabbitmq
    command: ["/bin/bash"]

networks:
  rabbitmq_net:
    driver: bridge
