version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.13
    container_name: rabbitmq_container  # Name the RabbitMQ container
    ports:
      - "5552:5552"
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_stream advertised_host localhost"
    networks:
      - rabbitmq_net

  debian:
    image: debian:latest
    container_name: debian_container  # Name the Debian container
    stdin_open: true  # To keep the container open for students to access
    tty: true         # Enables terminal support
    volumes:
      - ./student_code:/usr/src/app  # Mounts the local directory for student code
    networks:
      - rabbitmq_net
    depends_on:
      - rabbitmq
    command: ["/bin/bash"]

networks:
  rabbitmq_net:
    driver: bridge
